### ISSUE TITLE
Feat idea - allow user specifying custom timeout between requests to order list endpoint

### ISSUE THREAD

**Issue by vainia** [vainia/stepn-enhanced-filter#16]

**Comment by vainia** [comment]
Also, add a warning about IP address restrictions (update FAQs) and recommendations regarding VPN. Explain more Cloudflare Rate Limiting in FAQs

**Comment by vesnican** [comment]
Good idea, just got my IP banned for 24 hours (retry-after: 85934 in the response header now) after searching about 1500 sneakers.

**Comment by vainia** [comment]
#9 will be implemented with the PR for this issue
